services:
  minio:
    image: minio/minio:latest
    container_name: minio_server
    ports:
      - 9000:9000
      - 9001:9001
    networks:
      minio-network:
        ipv4_address: ${MINIO_IPV4_ADDRESS}
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: minio server /export --address :9000 --console-address :9001
    volumes:
      - ./.data/minio/data:/export
      - ./.data/minio/config:/root/.minio

networks:
  minio-network:
    external: true
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: ${DOCKER_SUBNET}
